/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package routeplannapp;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author mncrf
 */
public class RoutePlanGUI extends javax.swing.JFrame {

    /**
     * Creates new form RoutePlanGUI
     */
    public RoutePlanGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        mainBtn = new javax.swing.JButton();
        communityBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        returnSelectorLbl = new javax.swing.JLabel();
        routeSelectorLbl = new javax.swing.JLabel();
        bicycleBtn = new javax.swing.JRadioButton();
        walkBtn = new javax.swing.JRadioButton();
        publicTransBtn = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        answerTxtArea = new javax.swing.JTextArea();
        genPath = new javax.swing.JButton();
        routeCombo = new javax.swing.JComboBox<>();
        r3turnCombo = new javax.swing.JComboBox<>();
        readBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        mainBtn.setBackground(new java.awt.Color(255, 255, 255));
        mainBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainBtn.setForeground(new java.awt.Color(0, 0, 0));
        mainBtn.setText("Main:");
        mainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtnActionPerformed(evt);
            }
        });

        communityBtn.setBackground(new java.awt.Color(255, 255, 255));
        communityBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        communityBtn.setForeground(new java.awt.Color(0, 0, 0));
        communityBtn.setText("Community:");
        communityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        titleLbl.setText("Route Planner");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/routeplannapp/MainHubImage.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/routeplannapp/CommunityImage.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        returnSelectorLbl.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        returnSelectorLbl.setText("Return:");

        routeSelectorLbl.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        routeSelectorLbl.setText("Route:");

        bicycleBtn.setBackground(new java.awt.Color(102, 102, 102));
        btnGroup.add(bicycleBtn);
        bicycleBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bicycleBtn.setForeground(new java.awt.Color(0, 0, 0));
        bicycleBtn.setText("Bicycle");
        bicycleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bicycleBtnActionPerformed(evt);
            }
        });

        walkBtn.setBackground(new java.awt.Color(102, 102, 102));
        btnGroup.add(walkBtn);
        walkBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        walkBtn.setForeground(new java.awt.Color(0, 0, 0));
        walkBtn.setText("Walk");

        publicTransBtn.setBackground(new java.awt.Color(102, 102, 102));
        btnGroup.add(publicTransBtn);
        publicTransBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        publicTransBtn.setForeground(new java.awt.Color(0, 0, 0));
        publicTransBtn.setText("Public Transport");
        publicTransBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicTransBtnActionPerformed(evt);
            }
        });

        answerTxtArea.setBackground(new java.awt.Color(255, 255, 255));
        answerTxtArea.setColumns(20);
        answerTxtArea.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        answerTxtArea.setForeground(new java.awt.Color(0, 0, 0));
        answerTxtArea.setRows(5);
        answerTxtArea.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setViewportView(answerTxtArea);

        genPath.setBackground(new java.awt.Color(255, 255, 255));
        genPath.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genPath.setForeground(new java.awt.Color(0, 0, 0));
        genPath.setText("Generate Path:");
        genPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genPathActionPerformed(evt);
            }
        });

        routeCombo.setBackground(new java.awt.Color(102, 102, 102));
        routeCombo.setEditable(true);
        routeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O'Connell Street", "Pearse Station", "Earl Street", "Henry Street", "Grafton Street", " " }));
        routeCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                routeComboItemStateChanged(evt);
            }
        });
        routeCombo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                routeComboAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        routeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeComboActionPerformed(evt);
            }
        });

        r3turnCombo.setBackground(new java.awt.Color(102, 102, 102));
        r3turnCombo.setEditable(true);
        r3turnCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O'Connell Street\t", "Pearse Station", "Earl Street", "Henry Street", "Grafton Street" }));
        r3turnCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                r3turnComboItemStateChanged(evt);
            }
        });
        r3turnCombo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                r3turnComboAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        r3turnCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3turnComboActionPerformed(evt);
            }
        });

        readBtn.setBackground(new java.awt.Color(255, 255, 255));
        readBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        readBtn.setForeground(new java.awt.Color(0, 0, 0));
        readBtn.setText("Read");
        readBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLbl)
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(communityBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119)
                .addComponent(genPath)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(mainBtn)
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(returnSelectorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(r3turnCombo, 0, 134, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(routeSelectorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(routeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bicycleBtn)
                            .addComponent(walkBtn)
                            .addComponent(readBtn)
                            .addComponent(publicTransBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(publicTransBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bicycleBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(walkBtn)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(routeSelectorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(routeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainBtn)
                    .addComponent(returnSelectorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3turnCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(communityBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genPath)
                            .addComponent(readBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void communityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityBtnActionPerformed
        // TODO add your handling code here:
        CommunityGUI c = new CommunityGUI();
        c.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_communityBtnActionPerformed

    private void mainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtnActionPerformed
        // TODO add your handling code here:
        MainGUI m = new MainGUI();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainBtnActionPerformed

    private void bicycleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bicycleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bicycleBtnActionPerformed

    private void genPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genPathActionPerformed
        // TODO add your handling code here:
        int time;//time for user to get to his destination
        int co2=0;//amount of co2 user emitted using the selected mode of transport in grams
        Output mystructure;
        if (publicTransBtn.isSelected()){
            if(routeCombo.getSelectedItem()==("O'Connell Street")){
                if(r3turnCombo.getSelectedItem()==("Grafton Street")){
                     mystructure= new Output("O'Connell Street","Grafton Street","30",335);
                answerTxtArea.setText(mystructure.output());
                co2=335;
                time=30;
                
            }
                else if(r3turnCombo.getSelectedItem()=="Pearse Station"){
                     mystructure= new Output("O'Connell Street","Pearse Station","20",270);
                answerTxtArea.setText(mystructure.output());
                co2=270;
                time=20;
            }
                else if(r3turnCombo.getSelectedItem()=="Henry Street"){
                     mystructure= new Output("O'Connell Street","Henry Street","4",45);
                answerTxtArea.setText(mystructure.output());
                co2=45;
                time=4;
                }
                else if(r3turnCombo.getSelectedItem()=="Earl Street"){
                     mystructure= new Output("O'Connell Street","Earl Street","15",180);
                answerTxtArea.setText(mystructure.output());
                co2=180;
                time=15;
            
                    
                }
                
                
            }
            else if(routeCombo.getSelectedItem()=="Pearse Station"){
                if(r3turnCombo.getSelectedItem()=="O'Connell Street"){
                     mystructure= new Output("Pearse Station","O Connell Street","15",270);
                answerTxtArea.setText(mystructure.output());
                co2=270;
                time=15;
            }
                else if(r3turnCombo.getSelectedItem()=="Grafton Street"){
                    mystructure= new Output("Pearse Station","Grafton Street","25",175);
                answerTxtArea.setText(mystructure.output());
                co2=175;
                time=25;
            }
                else if(r3turnCombo.getSelectedItem()=="Henry Street"){
                    mystructure= new Output("Pearse Station","Henry Street","15",290);
                answerTxtArea.setText(mystructure.output());
                co2=290;
                time=15;
            }
                else if(r3turnCombo.getSelectedItem()=="Earl Street"){
                    mystructure= new Output("Pearse Station","Earl Street","10",140);
                answerTxtArea.setText(mystructure.output());
                co2=140;
                time=10;
            }
        }
            else if(routeCombo.getSelectedItem()=="Grafton Street"){
                if(r3turnCombo.getSelectedItem()=="O'Connell Street"){
                    mystructure= new Output("Grafton Street","O Connell Street","20",335);
                answerTxtArea.setText(mystructure.output());
                co2=335;
                time=20;
                }
            else if(r3turnCombo.getSelectedItem()=="Pearse Station"){
                mystructure= new Output("Grafton Street","Pearse Station","15",175);
                answerTxtArea.setText(mystructure.output());
                co2=175;     
                time=15;
            }
            else if(r3turnCombo.getSelectedItem()=="Henry Street"){
                mystructure= new Output("Grafton Street","Henry Street","20",200);
                answerTxtArea.setText(mystructure.output());
                co2=200;
                time=20;
            }
            else if(r3turnCombo.getSelectedItem()=="Earl Street"){
                mystructure= new Output("Grafton Street","Earl Street","30",360);
                answerTxtArea.setText(mystructure.output());
                co2=360;           
                time=30;
            }
            
                     
                
            }
            else if(routeCombo.getSelectedItem()=="Earl Street"){
                if(r3turnCombo.getSelectedItem()=="O'Connell Street"){
                    mystructure= new Output("Earl Street","O Connell Street","10",130);
                answerTxtArea.setText(mystructure.output());
                co2=130;
                time=10;
            }   
                else if(r3turnCombo.getSelectedItem()=="Pearse Station"){
                    mystructure= new Output("Earl Street","Pearse Station","10",140);
                answerTxtArea.setText(mystructure.output());
                co2=140;
                time=10;
            }
                else if(r3turnCombo.getSelectedItem()=="Grafton Street"){
                    mystructure= new Output("Earl Street","Grafton Street","25",330);
                answerTxtArea.setText(mystructure.output());
                co2=330;
                time=25;
            }   
                else if(r3turnCombo.getSelectedItem()=="Henry Street"){
                    mystructure= new Output("Earl Street","Henry Street","15",180);
                answerTxtArea.setText(mystructure.output());
                co2=180;
                time=15;
            }
            }
            else if(routeCombo.getSelectedItem()=="Henry Street"){
                if(r3turnCombo.getSelectedItem()=="O'Connell Street"){
                    mystructure= new Output("Henry Street","O Connell Street","25",290);
                answerTxtArea.setText(mystructure.output());
                co2=290;
                time=25;
        }
                if(r3turnCombo.getSelectedItem()=="Pearse Station"){
                    mystructure= new Output("Henry Street","Pearse Station","15",290);
                answerTxtArea.setText(mystructure.output());
                co2=290;
                time=15;
            }
                if(r3turnCombo.getSelectedItem()=="Grafton Street"){
                    mystructure= new Output("Henry Street","Grafton Street","30",350);
                answerTxtArea.setText(mystructure.output());
                co2=350;
                time=30;
            }
                if(r3turnCombo.getSelectedItem()=="Earl Street"){
                    mystructure= new Output("Henry Street","Earl Street","15",180);
                answerTxtArea.setText(mystructure.output());                
                co2=180;
                time=15;
            }
        }
            
        }
        if (walkBtn.isSelected()){
            if(routeCombo.getSelectedItem()==("O'Connell Street")){
                if(r3turnCombo.getSelectedItem()==("Grafton Street")){
                     mystructure= new Output("O'Connell Street","Grafton Street","15",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=15;
            }
                else if(r3turnCombo.getSelectedItem()=="Pearse Station"){
                     mystructure= new Output("O'Connell Street","Pearse Station","20",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=20;
            }
                else if(r3turnCombo.getSelectedItem()=="Henry Street"){
                     mystructure= new Output("O'Connell Street","Henry Street","4",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=4;
                }
                else if(r3turnCombo.getSelectedItem()=="Earl Street"){
                     mystructure= new Output("O'Connell Street","Earl Street","4",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=4;
            
                    
                }
                
                
            }
            else if(routeCombo.getSelectedItem()=="Pearse Station"){
                if(r3turnCombo.getSelectedItem()=="O'Connell Street"){
                     mystructure= new Output("Pearse Station","O Connell Street","20",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=20;
            }
                else if(r3turnCombo.getSelectedItem()=="Grafton Street"){
                    mystructure= new Output("Pearse Station","Grafton Street","15",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=15;
            }
                else if(r3turnCombo.getSelectedItem()=="Henry Street"){
                    mystructure= new Output("Pearse Station","Henry Street","20",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=20;
            }
                else if(r3turnCombo.getSelectedItem()=="Earl Street"){
                    mystructure= new Output("Pearse Station","Earl Street","15",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=15;
            }
        }
            else if(routeCombo.getSelectedItem()=="Grafton Street"){
                if(r3turnCombo.getSelectedItem()=="O'Connell Street"){
                    mystructure= new Output("Grafton Street","O Connell Street","15",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=15;
                }
            else if(r3turnCombo.getSelectedItem()=="Pearse Station"){
                mystructure= new Output("Grafton Street","Pearse Station","15",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;     
                time=15;
            }
            else if(r3turnCombo.getSelectedItem()=="Henry Street"){
                mystructure= new Output("Grafton Street","Henry Street","15",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=15;
            }
            else if(r3turnCombo.getSelectedItem()=="Earl Street"){
                mystructure= new Output("Grafton Street","Earl Street","15",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;   
                time=15;
            }
            
                     
                
            }
            else if(routeCombo.getSelectedItem()=="Earl Street"){
                if(r3turnCombo.getSelectedItem()=="O'Connell Street"){
                    mystructure= new Output("Earl Street","O Connell Street","5",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=5;
            }
                else if(r3turnCombo.getSelectedItem()=="Pearse Station"){
                    mystructure= new Output("Earl Street","Pearse Station","20",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=20;
            }
                else if(r3turnCombo.getSelectedItem()=="Grafton Street"){
                    mystructure= new Output("Earl Street","Grafton Street","15",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=15;
            }   
                else if(r3turnCombo.getSelectedItem()=="Henry Street"){
                    mystructure= new Output("Earl Street","Henry Street","13",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=13;
            }
            }
            else if(routeCombo.getSelectedItem()=="Henry Street"){
                if(r3turnCombo.getSelectedItem()=="O'Connell Street"){
                    mystructure= new Output("Henry Street","O Connell Street","5",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=5;
        }
                if(r3turnCombo.getSelectedItem()=="Pearse Station"){
                    mystructure= new Output("Henry Street","Pearse Station","20",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=20;
            }
                if(r3turnCombo.getSelectedItem()=="Grafton Street"){
                    mystructure= new Output("Henry Street","Grafton Street","15",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=15;
            }
                if(r3turnCombo.getSelectedItem()=="Earl Street"){
                    mystructure= new Output("Henry Street","Earl Street","3",0);
                answerTxtArea.setText(mystructure.output());                
                co2=0;
                time=3;
            }
        }
            
        }
        if (bicycleBtn.isSelected()){
            if(routeCombo.getSelectedItem()==("O'Connell Street")){
                if(r3turnCombo.getSelectedItem()==("Grafton Street")){
                     mystructure= new Output("O'Connell Street","Grafton Street","10",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=10;
            }
                else if(r3turnCombo.getSelectedItem()=="Pearse Station"){
                     mystructure= new Output("O'Connell Street","Pearse Station","10",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=10;
            }
                else if(r3turnCombo.getSelectedItem()=="Henry Street"){
                     mystructure= new Output("O'Connell Street","Henry Street","2",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=2;
                }
                else if(r3turnCombo.getSelectedItem()=="Earl Street"){
                     mystructure= new Output("O'Connell Street","Earl Street","3",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=3;
            
                    
                }
                
                
            }
            else if(routeCombo.getSelectedItem()=="Pearse Station"){
                if(r3turnCombo.getSelectedItem()=="O'Connell Street"){
                     mystructure= new Output("Pearse Station","O Connell Street","10",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=10;
                
            }
                else if(r3turnCombo.getSelectedItem()=="Grafton Street"){
                    mystructure= new Output("Pearse Station","Grafton Street","6",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=6;
            }
                else if(r3turnCombo.getSelectedItem()=="Henry Street"){
                    mystructure= new Output("Pearse Station","Henry Street","10",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=10;
            }
                else if(r3turnCombo.getSelectedItem()=="Earl Street"){
                    mystructure= new Output("Pearse Station","Earl Street","10",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=10;
            }
        }
            else if(routeCombo.getSelectedItem()=="Grafton Street"){
                if(r3turnCombo.getSelectedItem()=="O Connell Street"){
                    mystructure= new Output("Grafton Street","O Connell Street","5",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=5;
                }
            else if(r3turnCombo.getSelectedItem()=="Pearse Station"){
                mystructure= new Output("Grafton Street","Pearse Station","5",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;  
                time=5;
            }
            else if(r3turnCombo.getSelectedItem()=="Henry Street"){
                mystructure= new Output("Grafton Street","Henry Street","7",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=7;
            }
            else if(r3turnCombo.getSelectedItem()=="Earl Street"){
                mystructure= new Output("Grafton Street","Earl Street","10",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;    
                time=10;
            }
            
                     
                
            }
            else if(routeCombo.getSelectedItem()=="Earl Street"){
                if(r3turnCombo.getSelectedItem()=="O'Connell Street"){
                    mystructure= new Output("Earl Street","O Connell Street","3",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=3;
            }
                else if(r3turnCombo.getSelectedItem()=="Pearse Station"){
                    mystructure= new Output("Earl Street","Pearse Station","10",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=10;
            }
                else if(r3turnCombo.getSelectedItem()=="Grafton Street"){
                    mystructure= new Output("Earl Street","Grafton Street","10",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=10;
            }   
                else if(r3turnCombo.getSelectedItem()=="Henry Street"){
                    mystructure= new Output("Earl Street","Henry Street","5",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=5;
            }
            }
            else if(routeCombo.getSelectedItem()=="Henry Street"){
                if(r3turnCombo.getSelectedItem()=="O'Connell Street"){
                    mystructure= new Output("Henry Street","O Connell Street","3",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=3;
        }
                if(r3turnCombo.getSelectedItem()=="Pearse Station"){
                    mystructure= new Output("Henry Street","Pearse Station","10",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=10;
            }
                if(r3turnCombo.getSelectedItem()=="Grafton Street"){
                    mystructure= new Output("Henry Street","Grafton Street","10",0);
                answerTxtArea.setText(mystructure.output());
                co2=0;
                time=10;
            }
                if(r3turnCombo.getSelectedItem()=="Earl Street"){
                    mystructure= new Output("Henry Street","Earl Street","5",0);
                answerTxtArea.setText(mystructure.output());                
                co2=0;
                time=5;

                  
            }
        }
            
        }
        

       File file = new File("co2history.txt");// creates file co2history
        try 
            (FileWriter fw = new FileWriter(file, true); 
         BufferedWriter bw = new BufferedWriter(fw)) {
        bw.write(String.valueOf(co2));//writes co2 integer into a string
        bw.newLine();//creates a ne line to be easy readable
    JOptionPane.showMessageDialog(null, "The CO2 emission has been saved.");
} catch (IOException e) {
    JOptionPane.showMessageDialog(null, "An error occurred while saving your data: " + e.getMessage());
}
        
        
        
                
    }//GEN-LAST:event_genPathActionPerformed

    private void routeComboAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_routeComboAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_routeComboAncestorMoved

    private void routeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeComboActionPerformed
        // TODO add your handling code here:
        String selectedStreet = (String) routeCombo.getSelectedItem();//gets all streets from combo box
        String[] streets = {"O'Connell Street", "Grafton Street", "Pearse Station", "Henry Street", "Earl Street"};
        r3turnCombo.removeAllItems(); // Clears all streets 
                for (String street : streets) {
                    if (!street.equals(selectedStreet)) {
                        r3turnCombo.addItem(street); // Add streets except the selected one
                    }
                }
        
        
    }//GEN-LAST:event_routeComboActionPerformed

    private void routeComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_routeComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_routeComboItemStateChanged

    private void r3turnComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_r3turnComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_r3turnComboItemStateChanged

    private void r3turnComboAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_r3turnComboAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_r3turnComboAncestorMoved

    private void r3turnComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3turnComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3turnComboActionPerformed

    private void readBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Read Button not working.");

    }//GEN-LAST:event_readBtnActionPerformed

    private void publicTransBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicTransBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publicTransBtnActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoutePlanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoutePlanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoutePlanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoutePlanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoutePlanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea answerTxtArea;
    private javax.swing.JRadioButton bicycleBtn;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton communityBtn;
    private javax.swing.JButton genPath;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainBtn;
    private javax.swing.JRadioButton publicTransBtn;
    private javax.swing.JComboBox<String> r3turnCombo;
    private javax.swing.JButton readBtn;
    private javax.swing.JLabel returnSelectorLbl;
    private javax.swing.JComboBox<String> routeCombo;
    private javax.swing.JLabel routeSelectorLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JRadioButton walkBtn;
    // End of variables declaration//GEN-END:variables
}
